WebinarBlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: WebinarBlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        content:
            type: text
    lifecycleCallbacks: {  }
